### ISSUE TITLE
I got all the dump files & other things, now how do I create a mod menu (aimbot) for Garena free fire using those files in dnspy. I'm a beginner to this, so don't know what to do :p

### ISSUE THREAD

**Issue by TheBluePC5** [code-developers/freefire-esp-aimbot#1]

**Comment by krishpranav** [comment]
so you want to create a mod menu??

**Comment by TheBluePC5** [comment]
> so you want to create a mod menu??

Yes

**Comment by krishpranav** [comment]
check out these links hope it will be usefull for you:
https://github.com/LGLTeam/FreeFire-ESP-And-Aimbot-3
https://github.com/LGLTeam/FreeFire-ESP-And-Aimbot-2

**Comment by krishpranav** [comment]
you can able to see more repo like this and you can take them as a example and create your own:
https://github.com/search?q=free+fire+esp+aimbot

**Comment by TheBluePC5** [comment]
I got those files, all thanks to you, but can you please tell me how I should inject this into free fire? 😅

**Comment by krishpranav** [comment]
just build the apk through android studio and install the apk on your phone
